import Footer from "@/ui/Footer";
import "../public/globals.css";
import Header from "@/ui/Header";
import {MusicProvider} from "@/context/musicContext";
import {Toaster} from "react-hot-toast";
import FormMusic from "@/components/FormMusic";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body>
        <Toaster />
        <div className="sm:max-w-80 m-auto">
          <MusicProvider>
            <Header />
            <main>{children}</main>
            <footer className="sm:max-w-80 m-auto fixed left-0 right-0 bottom-0">
              <FormMusic />
              <Footer />
            </footer>
          </MusicProvider>
        </div>
      </body>
    </html>
  );
}
