import Footer from "@/ui/Footer";
import "../public/globals.css";
import Header from "@/ui/Header";
import { MusicProvider } from "@/context/musicContext";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Toaster />
        <div className="sm:max-w-96 mx-auto">
          <MusicProvider>
            <Header />
            <footer className="sm:max-w-96 mx-auto fixed left-0 right-0 bottom-0">
              {children}
              <Footer />
            </footer>
          </MusicProvider>
        </div>
      </body>
    </html>
  );
}
